# Generated by Django 4.2.30 on 2026-06-01 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='learning_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
