# Generated by Django 4.2.30 on 2026-06-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='resource_link',
            field=models.URLField(help_text='Link to uploaded document, drive asset, or file repo'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
